credentials:
  usernames:
    admin_user:
      name: Admin
      password: ${admin_user_password}
      email: ademola.atolagbe@avonhealthcare.com
    contactcenter_user:
      name: Contact Center Unit
      password: ${contactcenter_user_password}
      email: contactcenterunit@avonhealthcare.com
    medical_services_user:
      name: Medical Services Department
      password: ${medical_services_user_password}
      email: medicalservices@avonhealthcare.com
    audit_user:
      name: Internal Audit, Risk & Control
      password: ${audit_user_password}
      email: internalauditriskandcontroldept@avonhealthcare.com
cookie:
  name: my_app
  key: some_random_key
  expiry_days: 30
preauthorized:
  emails: []