credentials:
  usernames:
    admin_user:
      name: Admin
      password: Admin123*
      email: ademola.atolagbe@avonhealthcare.com
    contactcenter_user:
      name: Contact Center Unit
      password: Avon@123#
      email: contactcenterunit@avonhealthcare.com
    medical_services_user:
      name: Medical Services Department
      password: ${medical_services_user_password}
      email: Avon123#
    audit_user:
      name: Internal Audit, Risk & Control
      password: Audit123#
      email: internalauditriskandcontroldept@avonhealthcare.com
cookie:
  name: my_app
  key: some_random_key
  expiry_days: 30
preauthorized:
  emails: []